name: Trigger Vercel Deploy Hook

on:
  push:
    branches:
      - main

jobs:
  vercelDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: POST to Vercel Deploy Hook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_RYWPpwTYsidpNyPapwSJA0a3Wbh4/xdEgSqHvF2
